# Site settings
title: What Works
subtitle: Weaving Mentoring into Teaching, Research, and Service
email: whatworks@knowinnovation.com
description: 
baseurl: "/what-works" # the subpath of your site, e.g. /blog
url: "https://julia-figs.github.io/" # the base hostname & protocol for your site


# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url: http://www.knowinnovation.com
twitter_url: http://twitter.com/knowinnovation

# Build settings
markdown: kramdown

sass:
  style: compressed
